version: '3.6'  
services:  
  wiki:
    build:
      context: ./wiki
    container_name: wiki_connector
    environment:
      - MONGO_HOST=database
    depends_on:
      - database
  database:
    image: mongo
    container_name: wiki_mongo
    environment:
      - MONGO_INITDB_DATABASE=wiki
    volumes:
      - ./mongodata:/data/db
    ports:
      - '27017-27019:27017-27019'

