version: "3"
services:
  bot:
    container_name: botnode
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - database
  database:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/data