version: "3"
services:
  bot:
    container_name: botnode
    build: .
    ports:
      - "3000:3000"
    links:
      - database
    volumes:
      - .:/usr/src/app
  database:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/data
    logging:
      driver: none
